### ISSUE TITLE
Stale AbstractEdge Definition

### ISSUE THREAD

**Issue by iimpulse** [geneontology/obographs#108]
the latest ontology releases attach a field 'propertyType' to an edge causing downstream breaking changes.

**Comment by pnrobinson** [comment]
e.g., 
```
{
      "id" : "http://purl.org/dc/elements/1.1/creator",
      "type" : "PROPERTY",
      "propertyType" : "ANNOTATION"
    },
```
@ielis -- should we add this change to phenol ? We cannot currently load hp.json in phenol

**Comment by ielis** [comment]
I think Mike has been already working on a fix on Phenol's side, this should resolve the issues: https://github.com/monarch-initiative/phenol/pull/466

**Comment by matentzn** [comment]
Biiiiig relief if this turns out to work!
