### ISSUE TITLE
missing 'restrictions' property

### ISSUE THREAD

**Issue by balhoff** [geneontology/obographs#110]
In GO, we are trying to update to the latest obographs in ROBOT. We have been using owltools, which uses an older obographs release. We noticed this change, which currently upsets the ontobio JSON reader:

owltools:

```json
{
      "definedClassId" : "http://purl.obolibrary.org/obo/GO_0101013",
      "genusIds" : [ "http://purl.obolibrary.org/obo/GO_0005248", "http://purl.obolibrary.org/obo/GO_0008381" ],
      "restrictions" : [ ]
}
```

robot:

```json
{
      "definedClassId" : "http://purl.obolibrary.org/obo/GO_0101013",
      "genusIds" : [ "http://purl.obolibrary.org/obo/GO_0005248", "http://purl.obolibrary.org/obo/GO_0008381" ]
}
```

owltools outputs an empty `restrictions` array, but the newer obographs leaves it out. The schema doesn't mark it as optional: https://github.com/geneontology/obographs/blob/6676b10a5cce04707d75b9dd46fa08de70322b0b/schema/obographs-schema.json#L237

Does the obographs writer need a fix? Or should the schema be modified?

**Comment by balhoff** [comment]
@cmungall @julesjacobsen what do you think about this?

**Comment by cmungall** [comment]
the robot output is compliant with json-schema, see
https://stackoverflow.com/questions/16204871/what-is-the-difference-between-required-vs-optional-in-json-schema

sounds like ontobio needs fixed (or better: retired)

**Comment by balhoff** [comment]
Thanks @cmungall I didn't realize how that worked! Will open an issue at ontobio.
