### ISSUE TITLE
Term comments not present in go-plus.json

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/obographs#18]
As well as the issue (reported elsewhere) of the "is_obsolete" flag not being present in the JSON representation, I've also spotted that term comments are missing too.

**Comment by cmungall** [comment]
Both #17 and #19 are in 0.0.9 which has just been staged at mvncentral

if you want to experiment you can change the pom.xml for owltools. I'll do this sometime this week after which changes will propagate to http://purl.obolibrary.org/obo/go/extensions/go-plus.json

**Comment by dosumis** [comment]
I've just updated to the latest OWLtools, but using this, the complete set of meta keys is still:

{'definition', 'subsets', 'synonyms', 'xrefs'}

Compared to this for the released version of go-plus.json:

{'basicPropertyValues',
 'comments',
 'definition',
 'deprecated',
 'subsets',
 'synonyms',
 'xrefs'}

Does something still need to be done to propagate changes through to OWLtools?  I need this working quite urgently for VFB.

Cheers,
David

**Comment by cmungall** [comment]
You can always do a mvn build from this repo then run `ogger` script in this repo to use the latest from master.

Or make a PR to that updates the pom.xml in owltools to use the latest mvncentral version of this lib (this can be seen on the badge in the README.md in this repo). My latest commit (linked here) does this, so you should be good with a new owltools build for now, but it may lag again in the future.
