### ISSUE TITLE
Over-enthusiastic escaping of double quotes?

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/obographs#20]
There are a few cases where it looks like double quote characters embedded in a term's definition are being escaped with a bit too much zeal.

For example, this from the definition of GO_0061232:

...is a specialized epithelial cell that contains \\\"feet\\\" that interdigitate with the \\\"feet\\\" of other glomerular epithelial cells in the mesonephros.

Other terms that appear to be similarly affected are:
GO:0061256
GO:0061257
GO:0061258

**Comment by cmungall** [comment]
NSWYM - this is just standard JSON escaping? What parser are you using?

**Comment by cmungall** [comment]
Ah, I think you actually tried to use additional backslashes here but github escaped them...

the translation is fine. The source obo has 3 backslashes followed by a quote:

```
def: "The process whose specific outcome is the progression of the mesonephric glomerular epithelium over time, from its formation to the mature structure. The mesonephric glomerular epithelium is an epithelial tissue that covers the outer surfaces of the glomerulus in the mesonephros. The mesonephric glomerular epithelium consists of both parietal and visceral epithelium. Mesonephric glomerular parietal epithelial cells are specialized epithelial cells that form tight junctions as a barrier to protein transport. A mesonephric glomerular visceral epithelial cell is a specialized epithelial cell that contains \\\"feet\\\" that interdigitate with the \\\"feet\\\" of other glomerular epithelial cells in the mesonephros." [GOC:mtg_kidney_jan10]
```
