### ISSUE TITLE
Inconsistency between go-plus.json and go-plus.owl/obo

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/obographs#28]
In go-plus.json GO:0080039 is shown as deprecated, while is go-plus.owl/obo it still appears as a valid, live term.
`{
      "id" : "http://purl.obolibrary.org/obo/GO_0080039",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "http://purl.obolibrary.org/obo/IAO_0000231",
          "val" : "http://purl.obolibrary.org/obo/IAO_0000227"
        }, {
          "pred" : "http://purl.obolibrary.org/obo/IAO_0100001",
          "val" : "http://purl.obolibrary.org/obo/GO_0016762"
        } ],
        "deprecated" : true
      },
      "type" : "CLASS"
    }`

**Comment by cmungall** [comment]
What is the versionIRIs?

owl is fine:

```
    <!-- http://purl.obolibrary.org/obo/GO_0080039 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0080039">
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/GO_0016762"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

The .obo is lagging. It's not officially supported:

http://geneontology.org/page/download-ontology

However it's not ideal to have it be out of date. Do you actively use it?

**Comment by tonysawfordebi** [comment]
OK - this appears to have been a timing issue...
In <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/go/releases/2017-05-02/extensions/go-plus.owl"/> we have:
`<owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0080039">
    <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GO_0046527"/>
    <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Catalysis of the hydrolysis of a beta-(1,4) bond in the backbone of a xyloglucan and transfers the xyloglucanyl segment on to O-4 of the non-reducing terminal glucose residue of a xyloglucan or an oligosaccharide of xyloglucan.</obo:IAO_0000115>
    <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">molecular_function</oboInOwl:hasOBONamespace>
    <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GO:0080039</oboInOwl:id>
    <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">xyloglucan endotransglucosylase activity</rdfs:label>
</owl:Class>
<owl:Axiom>
    <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/GO_0080039"/>
    <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
    <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Catalysis of the hydrolysis of a beta-(1,4) bond in the backbone of a xyloglucan and transfers the xyloglucanyl segment on to O-4 of the non-reducing terminal glucose residue of a xyloglucan or an oligosaccharide of xyloglucan.</owl:annotatedTarget>
    <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">EC:2.4.1.207</oboInOwl:hasDbXref>
    <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GOC:ask</oboInOwl:hasDbXref>
    <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:1400418</oboInOwl:hasDbXref>
    <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:1554366</oboInOwl:hasDbXref>
</owl:Axiom>
`
while in <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/go/releases/2017-05-03/extensions/go-plus.owl"/> we have:

`<owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0080039">
    <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
    <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
    <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/GO_0016762"/>
    <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
</owl:Class>
`
So what I was seeing yesterday in go-plus.json was correct, but go-plus.owl/obo were lagging behind.

The only thing that I currently use go-plus.obo for is the extraction of taxon constraints, but the plan is to move across to consuming everything from go-plus.json as soon as the last few remaining wrinkles are ironed out.
