### ISSUE TITLE
Plug obograph code into different ontology conversion and release tools

### ISSUE THREAD

**Issue by cmungall** [geneontology/obographs#5]
- [x] robot - https://github.com/ontodev/robot/issues/94
- [x] owltools DONE; use `-o -f json foo.json`
- [x] oort DONE

**Comment by dosumis** [comment]
Does this ticket cover plans for conversion from obo-graph to OWL or should I start a new ticket?  

I can think of lots of use-cases for working in this direction, e.g. a pure Python implementation of DOS-DPs (limited to suitable simple design patterns).

**Comment by cmungall** [comment]
Let's do a new ticket for this

**Comment by althonos** [comment]
@cmungall: ontodev/robot#94 was closed so you can probably close this as well :smile:
