### ISSUE TITLE
Create maven central release for fix of missing synonym type

### ISSUE THREAD

**Issue by pnrobinson** [geneontology/obographs#54]
@cmungall

**Comment by cmungall** [comment]
This is in reference to #38

**Comment by cmungall** [comment]
@balhoff @julesjacobsen would you be able to help?

**Comment by balhoff** [comment]
I think I've successfully released it. Please check! @cmungall can you give me permissions here so I can push my tag `v0.2.0`.

**Comment by pnrobinson** [comment]
Thanks! I have integrated this into phenol and it is working. I will close.
