### ISSUE TITLE
Need a property "mergedWith" or something similar for obsolete terms

### ISSUE THREAD

**Issue by matentzn** [geneontology/obographs#68]
So we have two Terms:

A "label 1"
B "label 2"

We merge them both into B "label 2"

There should be some way to understand from the JSON that A was merged into B.

**Comment by balhoff** [comment]
There is a pattern for this embedded in the OBO to OWL conversion in OWL API:

AnnotationAssertion([has obsolescence reason](http://purl.obolibrary.org/obo/IAO_0000231) GO:2000695 [terms merged](http://purl.obolibrary.org/obo/IAO_0000227))
AnnotationAssertion([term replaced by](http://purl.obolibrary.org/obo/IAO_0100001) GO:2000695 GO:0000920)
AnnotationAssertion(owl:deprecated <http://purl.obolibrary.org/obo/GO_2000695> "true"^^xsd:boolean)

**Comment by cmungall** [comment]
the json just follows the owl here, so I think we can close this?

**Comment by matentzn** [comment]
Sure I dont know why I made that issue anymore.
